<?php

namespace MailPoetVendor;

// autoload.php @generated by Composer
require_once __DIR__ . '/composer/autoload_real.php';
return \MailPoetVendor\ComposerAutoloaderInit8fd27f0181dae894e61714e4e2b08146::getLoader();
